from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('blog-grid/', views.blog_grid, name='blog_grid'),
    path('blogs/', views.blog_list, name='blog_list'),
    path('blog-details/', views.blog_details, name='blog_details'),
    path('contact/', views.contact, name='contact'),
    path('how-it-works/', views.how_it_works, name='how_it_works'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    # Password reset flow
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='urbanapp/forgot-password.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='urbanapp/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='urbanapp/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='urbanapp/password_reset_complete.html'), name='password_reset_complete'),


path('reset-password/', views.reset_password, name='reset_password'),
    # OTP-based SMS login
    path('login/otp/request/', views.otp_request, name='login_otp_request'),
    path('login/otp/verify/', views.otp_verify, name='login_otp_verify'),
    # Google OAuth placeholder
    path('login/google/', views.google_login, name='login_google'),
    path('services-list/', views.services, name='services'),
    path('service-details/', views.servicedetails, name='servicesdetails'),
    path('categories/', views.categories, name='categories'),
    path('providers/', views.providers, name='providers'),
    path('provider-details/', views.provider_details, name='provider_details'),
    path('create-service/', views.create_service, name='create_service'),
    path('user-dashboard/', views.user_dashboard, name='user_dashboard'),
    path('user-booking-list/', views.user_booking_list, name='user_booking_list'),
    path('favourites/', views.favourites, name='favourites'),
    path('customer-wallet/', views.user_wallet, name='user_wallet'),
    path('customer-reviews/', views.user_reviews, name='user_reviews'),
    path('user-chat/', views.user_chat, name='user_chat'),
    path('account-settings/', views.account_settings, name='account_settings'),
    path('provider/dashboard/', views.provider_dashboard, name='provider_dashboard'),
    path('provider/services/', views.provider_services, name='provider_services'),
    path('provider/booking/', views.provider_booking, name='provider_booking'),
    path('provider/staff/', views.provider_staff, name='provider_staff'),
    path('provider/customers/', views.provider_customers, name='provider_customers'),
    path('provider/payout/', views.provider_payout, name='provider_payout'),
    path('provider/holiday/', views.provider_holiday, name='provider_holiday'),
    path('provider/coupons/', views.provider_coupons, name='provider_coupons'),
    path('provider/offers/', views.provider_offers, name='provider_offers'),
    path('provider/reviews/', views.provider_reviews, name='provider_reviews'),
    path('provider/enquiry/', views.provider_enquiry, name='provider_enquiry'),
    path('provider/earnings/', views.provider_earnings, name='provider_earnings'),
    path('provider/chat/', views.provider_chat, name='provider_chat'),
    path('provider/appointment-settings/', views.provider_appointment_settings, name='provider_appointment_settings'),
    path('provider/accounts-settings/', views.provider_accounts_settings, name='provider_accounts_settings'),
    path('provider/social-profile/', views.provider_social_profile, name='provider_social_profile'),
    path('provider/security-settings/', views.provider_security_settings, name='provider_security_settings'),
    path('provider/plan/', views.provider_plan, name='provider_plan'),
    path('provider/payment-settings/', views.provider_payment_settings, name='provider_payment_settings'),
    path('provider/notifications/', views.provider_notifications, name='provider_notifications'),
    path('provider/connected-apps/', views.provider_connected_apps, name='provider_connected_apps'),
    path('provider/verification/', views.provider_verification, name='provider_verification'),
    path('provider/delete-account/', views.provider_delete_account, name='provider_delete_account'),
    path('provider/login/', views.provider_login, name='provider_login'),
    path('provider/register/', views.provider_register, name='provider_register'),
    # Provider password reset (separate from user)
    path('provider/password-reset/', views.ProviderPasswordResetView.as_view(), name='provider_password_reset'),
    path('provider/password-reset/done/', views.ProviderPasswordResetDoneView.as_view(), name='provider_password_reset_done'),
    path('provider/reset/<uidb64>/<token>/', views.ProviderPasswordResetConfirmView.as_view(), name='provider_password_reset_confirm'),
    path('provider/reset/done/', views.ProviderPasswordResetCompleteView.as_view(), name='provider_password_reset_complete'),

    path('admin/', views.admindash, name='admindash'),
    path('admin/add-service/', views.add_service, name='add_service'),
    path('admin/services/', views.admin_service, name='admin_service'),
    path('admin/service-settings/', views.admin_service_settings, name='admin_service_settings'),
    path('admin/sub-categories/', views.admin_sub_categories, name='admin_sub_categories'),
    path('admin/categories/', views.admin_categories, name='admin_categories'),
    path('admin/signin/', views.admin_signin, name='admin_signin'),
    path('admin/signup/', views.admin_register, name='admin_register'),
    # Admin password reset (separate from user password reset)
    path('admin/password-reset/', views.AdminPasswordResetView.as_view(), name='admin_password_reset'),
    path('admin/password-reset/done/', views.AdminPasswordResetDoneView.as_view(), name='admin_password_reset_done'),
    path('admin/reset/<uidb64>/<token>/', views.AdminPasswordResetConfirmView.as_view(), name='admin_password_reset_confirm'),
    path('admin/reset/done/', views.AdminPasswordResetCompleteView.as_view(), name='admin_password_reset_complete'),


]
